meta_title: "Rhythm & Soul"
meta_description: "Discover music event through your playlists"
meta_image: "image.jpg" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
