meta_title: "Rhythm & Soul - Discover music events through your playlists"
meta_description: "The best platform to find gigs only for artists you actually listen to. Connect your Spotify account, let us scan your tracks and that's it! You're all set up to find your next local concert, festival or DJ set."
meta_image: "banner-meta-tags.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@rhythm_and_soul" # indispensable pour les Twitter Cards
